<?php
/**
 * @file
 * Code for the VIH Viggo feature.
 */

include_once 'vih_viggo.features.inc';

/**
 * Implements hook_field_access().
 */
function vih_viggo_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] == 'viggo_imported_text' AND $op == 'edit') {
    // Only allow admins to edit field value.
    return user_access('bypass node access', $account);
  }
  return TRUE;
}

/**
 * Implements hook_field_formatter_info().
 *
 * Adds formatter to display calendar items for Viggo without unneccessary information
 */
function vih_viggo_field_formatter_info() {
  return array(
    'vih_viggo_formatter' => array(
      'label' => t('Viggo Calendar Description'),
      'field types' => array('text_long'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function vih_viggo_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  foreach ($items as $delta => $item) {
    $text = $item['safe_value'];
  }

  if (isset($text)) {
    $text = str_replace("Beskrivelse:", '', $text);
    $text = strstr($text, 'Opdateret: ', TRUE);
    // Assign it to the #markup of the element.
    $element[0]['#markup'] = check_markup($text, 'viggo_imported_text');
  }
  return $element;
}
