<?php
/**
 * @file
 * Code for the VIH Viggo feature.
 */

include_once 'vih_viggo.features.inc';

/**
 * @file
 * Adds formatter to display calendar items for Viggo properly
 */

/**
 * Implements hook_field_formatter_info().
 *
 * Adds formatter to display calendar items for Viggo without unneccessary information
 */
function vih_viggo_field_formatter_info() {
  return array(
    'vih_viggo_formatter' => array(
      'label' => t('Viggo Calendar Description'),
      'field types' => array('text_with_summary', 'text_long'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function vih_viggo_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  foreach ($items as $delta => $item) {
    $text = $item['safe_value'];
  }

  if (isset($text)) {
    $text = str_replace("Beskrivelse:", '', $text);
    $text = strstr($text, 'Opdateret: ', TRUE);
    // Assign it to the #markup of the element.
    $element[0]['#markup'] = strip_tags($text);
  }
  return $element;
}
